### ISSUE TITLE
Thanks and a request for shell quoting explanation

### ISSUE THREAD

**Issue by LosAlamosAl** [alexharv074/alexharv074.github.io#5]
Regarding `2021-03-15-how-to-write-an-aws-cli-script-part-i-patterns.md`:

First, you saved my bacon with this post. Thanks!

Second, it would be useful to have a note describing the shell-fu that enables this:

```bash
'StackResourceSummaries[?ResourceType==`'"$resource_type"'`].PhysicalResourceId'
```

I can't decipher the quoting that's going on in that parameter substitution of `$resource_type`!

**Comment by alex-harvey-z3q** [comment]
Hi @LosAlamosAl I only just saw this and if you did not figure it out here's an explanation:
1. In order to include a backtick ``` ` ``` inside a string it is necessary to enclode the string in single quotes.
2. In order to include a variable in a string it must be enclosed in double quotes.

This leaves us without many great options than to use single quotes for the first part of the string and then double quotes for the variable. It might help to look at a simpler example e.g.
```
% echo 'foo'"bar"'baz'
foobarbaz
% echo 'foo`'"bar"'`baz'
foo`bar`baz
```

Note that for these reasons I rarely use JMESPath these days and prefer to just always use JQ since it's more flexible in this regard. Instead of 
```
'StackResourceSummaries[?ResourceType==`'"$resource_type"'`].PhysicalResourceId'
```
You can instead use JQ and have 
```
jq --arg r "$resource_type" '.StackResourceSummaries[] | select(.ResourceType == $r) | .PhysicalResourceId' stack_resources.json
```
